#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=03:00:00
#PBS -N gsw0.1_10
#PBS -e gsw0.1_10.perr
#PBS -o gsw0.1_10.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.1b2/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.1b2/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.1b2/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.1_10.dmc &> gsw0.1_10.dmc.out
