#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=03:00:00
#PBS -N gsw0.7_2
#PBS -e gsw0.7_2.perr
#PBS -o gsw0.7_2.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.7b3/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.7b3/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.7b3/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.7_2.dmc &> gsw0.7_2.dmc.out
