#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=02:00:00
#PBS -N gsw1.0_1
#PBS -e gsw1.0_1.perr
#PBS -o gsw1.0_1.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw1.0b2/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw1.0b2/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw1.0b2/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw1.0_1.dmc &> gsw1.0_1.dmc.out
