#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=03:00:00
#PBS -N gsw0.6_6
#PBS -e gsw0.6_6.perr
#PBS -o gsw0.6_6.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.6b0/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.6b0/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.6b0/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.6_6.dmc &> gsw0.6_6.dmc.out
