#!/bin/bash
#PBS -q low
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N gsw0.4_4
#PBS -e gsw0.4_4.perr
#PBS -o gsw0.4_4.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.4b2/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.4b2/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.4b2/* .
aprun -n 32 /u/sciteam/$USER/fork/bin/qwalk gsw0.4_4.vmc &> gsw0.4_4.vmc.out
