#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=02:00:00
#PBS -N gsw0.2_1
#PBS -e gsw0.2_1.perr
#PBS -o gsw0.2_1.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_extra_extra/gsw0.2b0/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_extra_extra/gsw0.2b0/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_extra_extra/gsw0.2b0/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.2_1.dmc &> gsw0.2_1.dmc.out
