#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N ex_s_Ndet10_gsw0.7_24
#PBS -e ex_s_Ndet10_gsw0.7_24.perr
#PBS -o ex_s_Ndet10_gsw0.7_24.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run2s/
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run2s/
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run2s//* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex_s_Ndet10_gsw0.7_24.vmc &> ex_s_Ndet10_gsw0.7_24.vmc.out
