#!/bin/bash
#PBS -q low
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N gsw0.2_2
#PBS -e gsw0.2_2.perr
#PBS -o gsw0.2_2.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b1/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b1/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b1/* .
aprun -n 32 /u/sciteam/$USER/fork/bin/qwalk gsw0.2_2.vmc &> gsw0.2_2.vmc.out
