#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=03:00:00
#PBS -N gsw0.4_9
#PBS -e gsw0.4_9.perr
#PBS -o gsw0.4_9.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.4b4/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.4b4/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_d10_s1/gsw0.4b4/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.4_9.dmc &> gsw0.4_9.dmc.out
