#!/bin/bash 
#PBS -q low 
#PBS -l nodes=2:ppn=32:xe 
#PBS -l walltime=04:00:00 
#PBS -N gs3vmc_tbdm
#PBS -e gs3vmc_tbdm.perr 
#PBS -o gs3vmc_tbdm.pout 
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/base
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/base
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/base/* .
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/req_files/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk gs3.vmc_tbdm &> gs3.vmc_tbdm.out
