#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=02:00:00
#PBS -N gsw-1.0_1
#PBS -e gsw-1.0_1.perr
#PBS -o gsw-1.0_1.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_extra_3/gsw-1.0b1/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_extra_3/gsw-1.0b1/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_extra_3/gsw-1.0b1/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw-1.0_1.dmc &> gsw-1.0_1.dmc.out
