#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 2Delta_s_Ndet10_gsw0.7_23
#PBS -e 2Delta_s_Ndet10_gsw0.7_23.perr
#PBS -o 2Delta_s_Ndet10_gsw0.7_23.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1s/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 2Delta_s_Ndet10_gsw0.7_23.vmc &> 2Delta_s_Ndet10_gsw0.7_23.vmc.out
