#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 2X_s_Ndet10_gsw0.7_8
#PBS -e 2X_s_Ndet10_gsw0.7_8.perr
#PBS -o 2X_s_Ndet10_gsw0.7_8.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1s/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 2X_s_Ndet10_gsw0.7_8.vmc &> 2X_s_Ndet10_gsw0.7_8.vmc.out
