#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 2Y_s_Ndet10_gsw0.7_21
#PBS -e 2Y_s_Ndet10_gsw0.7_21.perr
#PBS -o 2Y_s_Ndet10_gsw0.7_21.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1s/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 2Y_s_Ndet10_gsw0.7_21.vmc &> 2Y_s_Ndet10_gsw0.7_21.vmc.out
