#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 4SigmaM_s_Ndet10_gsw0.7_18
#PBS -e 4SigmaM_s_Ndet10_gsw0.7_18.perr
#PBS -o 4SigmaM_s_Ndet10_gsw0.7_18.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1s/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 4SigmaM_s_Ndet10_gsw0.7_18.vmc &> 4SigmaM_s_Ndet10_gsw0.7_18.vmc.out
