#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N ex_a_Ndet10_gsw0.8_18
#PBS -e ex_a_Ndet10_gsw0.8_18.perr
#PBS -o ex_a_Ndet10_gsw0.8_18.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run3a/
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run3a/
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run3a//* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex_a_Ndet10_gsw0.8_18.vmc &> ex_a_Ndet10_gsw0.8_18.vmc.out
