#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N ex2_s_Ndet10_gsw0.7_37
#PBS -e ex2_s_Ndet10_gsw0.7_37.perr
#PBS -o ex2_s_Ndet10_gsw0.7_37.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s/
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1s/
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1s//* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex2_s_Ndet10_gsw0.7_37.vmc &> ex2_s_Ndet10_gsw0.7_37.vmc.out
