#!/bin/bash
#PBS -q low
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N gsw0.2_4
#PBS -e gsw0.2_4.perr
#PBS -o gsw0.2_4.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b0/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b0/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s3/gsw0.2b0/* .
aprun -n 32 /u/sciteam/$USER/fork/bin/qwalk gsw0.2_4.vmc &> gsw0.2_4.vmc.out
