#!/bin/bash 
#PBS -q debug 
#PBS -l nodes=2:ppn=32:xe 
#PBS -l walltime=00:30:00
#PBS -N Cuvtz0_B3LYP_s3_g0.1_cAll.vmc
#PBS -e Cuvtz0_B3LYP_s3_g0.1_cAll.vmc.perr 
#PBS -o Cuvtz0_B3LYP_s3_g0.1_cAll.vmc.pout 
mkdir -p /scratch/sciteam/$USER/./nchoose10_sgn2/test
cd /scratch/sciteam/$USER/./nchoose10_sgn2/test
cp /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP_s3_g0.1_cAll.vmc .
cp /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP_s3_g0.1.slater .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP.optjast3 .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP.sys .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP.orb .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYP.basis .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYPiao.orb .
cp -u /u/sciteam/$USER/cuo/qwalk/cutoff_test/Cuvtz0_B3LYPiao.basis .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk Cuvtz0_B3LYP_s3_g0.1_cAll.vmc &> Cuvtz0_B3LYP_s3_g0.1_cAll.vmc.out
