#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N ex2_s_Ndet10_gsw0.7_26
#PBS -e ex2_s_Ndet10_gsw0.7_26.perr
#PBS -o ex2_s_Ndet10_gsw0.7_26.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run2s/
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run2s/
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run2s//* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex2_s_Ndet10_gsw0.7_26.vmc &> ex2_s_Ndet10_gsw0.7_26.vmc.out
