#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N ex2_a_Ndet10_gsw0.8_50
#PBS -e ex2_a_Ndet10_gsw0.8_50.perr
#PBS -o ex2_a_Ndet10_gsw0.8_50.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run2a
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run2a
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run2a/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex2_a_Ndet10_gsw0.8_50.vmc &> ex2_a_Ndet10_gsw0.8_50.vmc.out
