#!/bin/bash
#PBS -q low
#PBS -l nodes=8:ppn=32:xe
#PBS -l walltime=02:00:00
#PBS -N gsw0.6_4
#PBS -e gsw0.6_4.perr
#PBS -o gsw0.6_4.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.6b1/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.6b1/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.6b1/* .
aprun -n 256 /u/sciteam/$USER/fork/bin/qwalk gsw0.6_4.dmc &> gsw0.6_4.dmc.out
