#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N ex2_a_Ndet10_gsw0.8_7
#PBS -e ex2_a_Ndet10_gsw0.8_7.perr
#PBS -o ex2_a_Ndet10_gsw0.8_7.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run3a/
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run3a/
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run3a//* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk ex2_a_Ndet10_gsw0.8_7.vmc &> ex2_a_Ndet10_gsw0.8_7.vmc.out
