#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 2Delta_a_Ndet10_gsw0.8_17
#PBS -e 2Delta_a_Ndet10_gsw0.8_17.perr
#PBS -o 2Delta_a_Ndet10_gsw0.8_17.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1a/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 2Delta_a_Ndet10_gsw0.8_17.vmc &> 2Delta_a_Ndet10_gsw0.8_17.vmc.out
