#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 2X_a_Ndet10_gsw0.8_16
#PBS -e 2X_a_Ndet10_gsw0.8_16.perr
#PBS -o 2X_a_Ndet10_gsw0.8_16.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1a/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 2X_a_Ndet10_gsw0.8_16.vmc &> 2X_a_Ndet10_gsw0.8_16.vmc.out
