#!/bin/bash
#PBS -q low
#PBS -l nodes=2:ppn=32:xe
#PBS -l walltime=04:00:00
#PBS -N 4Phi_a_Ndet10_gsw0.8_8
#PBS -e 4Phi_a_Ndet10_gsw0.8_8.perr
#PBS -o 4Phi_a_Ndet10_gsw0.8_8.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cd /scratch/sciteam/$USER/cuo/qwalk/vmc/run1a
cp -u /u/sciteam/$USER/cuo/qwalk/vmc/run1a/* .
aprun -n 64 /u/sciteam/$USER/fork/bin/qwalk 4Phi_a_Ndet10_gsw0.8_8.vmc &> 4Phi_a_Ndet10_gsw0.8_8.vmc.out
