#!/bin/bash
#PBS -q low
#PBS -l nodes=1:ppn=32:xe
#PBS -l walltime=01:00:00
#PBS -N gsw0.8_3
#PBS -e gsw0.8_3.perr
#PBS -o gsw0.8_3.pout
mkdir -p /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.8b2/
cd /scratch/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.8b2/
cp -u /u/sciteam/$USER/cuo/qwalk/ub3lyp_min_s1/gsw0.8b2/* .
aprun -n 32 /u/sciteam/$USER/fork/bin/qwalk gsw0.8_3.vmc &> gsw0.8_3.vmc.out
