#!/bin/bash 
#PBS -q normal
#PBS -l nodes=2:ppn=32:xe 
#PBS -l walltime=01:00:00
#PBS -N Cuvtz0_B3LYP_s5_g0.9.vmc
#PBS -e Cuvtz0_B3LYP_s5_g0.9.vmc.perr 
#PBS -o Cuvtz0_B3LYP_s5_g0.9.vmc.pout 
mkdir -p /scratch/sciteam/$USER/./nchoose10_sgn1
cd /scratch/sciteam/$USER/./nchoose10_sgn1
cp /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP_s5_g0.9.vmc .
cp /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP_s5_g0.9.slater .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP.optjast3 .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP.sys .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP.orb .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYP.basis .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYPiao.orb .
cp -u /u/sciteam/$USER/cuo/qwalk/sampling_test/./nchoose10_sgn1/Cuvtz0_B3LYPiao.basis .
aprun -n 64 /u/sciteam/$USER/mainline/bin/qwalk Cuvtz0_B3LYP_s5_g0.9.vmc &> Cuvtz0_B3LYP_s5_g0.9.vmc.out
